### ISSUE TITLE
Deactivate / unbind

### ISSUE THREAD

**Issue by antoniobrandao** [omichelsen/simple-slideshow#1]
Hello,

Is there a method to deactivate / unbind the slideshow? I intend to reuse simple-slideshow in a single page web-app, I'm concerned with unbinded event listeners and possible memory leaks.

**Comment by omichelsen** [comment]
I have just released a new version adding a `.destroy()` function to clean up resources.

This changes the return value from element to an instance of the `SlideShow()` class though, so this is a breaking change.

**Comment by antoniobrandao** [comment]
Great stuff! Thanks
